name: e2e tests
on: [deployment_status]
jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress Base URL
        run: echo ${{ github.event.deployment_status.target_url }}
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
        with:
          project: ./packages/frontend/e2e
          browser: chrome
