name: lint and tests

on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup node 
      - uses: actions/setup-node@v3
        with: 
          node-version: 16.10.x
          cache: yarn
          
      - name: install
        run: yarn install 

      - name: lint
        run: yarn lint

      - name: tests
        run: yarn test 

