name: lint and tests

on: [push]
jobs:
  build:
    name: lint and tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup node 
      - uses: actions/setup-node@v3
        with: 
          node-version: 16.13.x
          cache: yarn
      - name: install
        run: yarn install 

      - name: lint
        run: yarn lint

      - name: tests
        run: yarn test 

